parameters:
    estarRdaBundle.UserCheck.class: estar\rda\RdaBundle\Controller\UserCheckController
services:
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    estarRdaBundle.UserCheck:
        class: "%estarRdaBundle.UserCheck.class%"
        arguments:
          session: @session

    usercheck.notify:
        class: estar\rda\RdaBundle\Controller\UserCheckController
        arguments:
           em: "@doctrine.orm.entity_manager"
           user: "@security.context"
           session: "@session"

#services:
#    estar_rda.example:
#        class: estar\rda\RdaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    