parameters:
    estarRdaBundle.UserCheck.class: estar\rda\RdaBundle\Controller\UserCheckController
services:
    info_utente:
        class: estar\rda\RdaBundle\Services\InfoUtente
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    estarRdaBundle.UserCheck:
        class: "%estarRdaBundle.UserCheck.class%"
        arguments:
        session: @session

#services:
#    estar_rda.example:
#        class: estar\rda\RdaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    