parameters:
    estarRdaBundle.UserCheck.class: estar\rda\RdaBundle\Controller\UserCheckController
services:
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    estarRdaBundle.UserCheck:
        class: "%estarRdaBundle.UserCheck.class%"
        arguments:
          session: @session

    usercheck.notify:
        class: estar\rda\RdaBundle\Controller\UserCheckController
        arguments:
           em: "@doctrine.orm.entity_manager"
           user: "@security.context"
           session: "@session"

    model.richiesta:
        class: estar\rda\RdaBundle\Model\RichiestaModel
        arguments:
          em: "@doctrine.orm.entity_manager"
          user: "@security.context"
          session: "@session"

    model.campo:
        class: estar\rda\RdaBundle\Model\CampoModel
        arguments:
          em: "@doctrine.orm.entity_manager"
          user: "@security.context"

#services:
#    estar_rda.example:
#        class: estar\rda\RdaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    namer.richiesta_documento:
        class: estar\rda\RdaBundle\Namer\Namer
        tags:
            - { name: filePath }

    directory_namer.richiesta_documento:
            class: estar\rda\RdaBundle\Namer\DirectoryNamer
            tags:
                - { name: filePath }