<?php
/**
 * Created by PhpStorm.
 * User: francesco.galli
 * Date: 25/11/2015
 * Time: 16.04
 */

namespace estar\rda\RdaBundle\Controller;


use FOS\UserBundle\Controller\ProfileController;
use Symfony\Component\HttpFoundation\Request;

class ProfileExtendedController extends ProfileController
{

    /**
     * Sovrascrittura della edit action del controller
     * @param Request $request
     * @return null|\Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request)
    {
        return parent::editAction($request); // TODO: Change the autogenerated stub
    }


}