prog_test_homepage:
    path:     /hello/{name}
    defaults: { _controller: estarRdaBundle:DemoClient:hello }

SistematicaClient:
    path: /sistematicaclient/{idPratica}
    defaults: { _controller: estarRdaBundle:SistematicaClient:index}

estar_rda:
    resource: "@estarRdaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@estarRdaBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_besimple_soap:
    resource: "@BeSimpleSoapBundle/Resources/config/routing/webservicecontroller.xml"
    prefix:   /ws
