# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    info_utente:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.form.registration:
        class: estar\rda\RdaBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

  app.form.profile:
        class: estar\rda\RdaBundle\Form\ProfileType
        tags:
             - { name: form.type, alias: app_user_profile }

  navbar.twig_extension:
          class: estar\rda\RdaBundle\Twig\NavbarExtension
          public: false
          tags:
              - { name: twig.extension }
          arguments:
                      em: "@doctrine.orm.entity_manager"
                      user: "@security.context"
                      session: "@session"

  sidebar.twig_extension:
            class: estar\rda\RdaBundle\Twig\SidebarExtension
            public: false
            tags:
                - { name: twig.extension }
            arguments:
                        user: "@security.context"
  fos_user.doctrine_registry:
            alias: doctrine

  form_template_factory:
        class: estar\rda\RdaBundle\Form\FormTemplateService
        arguments:
            user:   "@usercheck.notify"
            router: "@router"
            em:     "@doctrine.orm.entity_manager"
