
package it.isharedoc.schemas.instance;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InstancePort", targetNamespace = "http://www.isharedoc.it/schemas/instance")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InstancePort {


    /**
     * 
     * @param taskSearchRequest
     * @return
     *     returns it.isharedoc.schemas.instance.TaskSearchResponse
     */
    @WebMethod(operationName = "TaskSearch")
    @WebResult(name = "TaskSearchResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "TaskSearchResponse")
    public TaskSearchResponse taskSearch(
        @WebParam(name = "TaskSearchRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "TaskSearchRequest")
        TaskSearchRequest taskSearchRequest);

    /**
     * 
     * @param instanceActivityCreateRequest
     * @return
     *     returns it.isharedoc.schemas.instance.InstanceActivityCreateResponse
     */
    @WebMethod(operationName = "InstanceActivityCreate")
    @WebResult(name = "InstanceActivityCreateResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceActivityCreateResponse")
    public InstanceActivityCreateResponse instanceActivityCreate(
        @WebParam(name = "InstanceActivityCreateRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceActivityCreateRequest")
        InstanceActivityCreateRequest instanceActivityCreateRequest);

    /**
     * 
     * @param instanceOperationRequest
     * @return
     *     returns it.isharedoc.schemas.instance.InstanceOperationResponse
     */
    @WebMethod(operationName = "InstanceOperation")
    @WebResult(name = "InstanceOperationResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceOperationResponse")
    public InstanceOperationResponse instanceOperation(
        @WebParam(name = "InstanceOperationRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceOperationRequest")
        InstanceOperationRequest instanceOperationRequest);

    /**
     * 
     * @param instancePreviewRequest
     * @return
     *     returns it.isharedoc.schemas.instance.InstancePreviewResponse
     */
    @WebMethod(operationName = "InstancePreview")
    @WebResult(name = "InstancePreviewResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstancePreviewResponse")
    public InstancePreviewResponse instancePreview(
        @WebParam(name = "InstancePreviewRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstancePreviewRequest")
        InstancePreviewRequest instancePreviewRequest);

    /**
     * 
     * @param instanceMessageUpdateRequest
     * @return
     *     returns it.isharedoc.schemas.instance.InstanceMessageUpdateResponse
     */
    @WebMethod(operationName = "InstanceMessageUpdate")
    @WebResult(name = "InstanceMessageUpdateResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceMessageUpdateResponse")
    public InstanceMessageUpdateResponse instanceMessageUpdate(
        @WebParam(name = "InstanceMessageUpdateRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceMessageUpdateRequest")
        InstanceMessageUpdateRequest instanceMessageUpdateRequest);

    /**
     * 
     * @param instanceMessageCreateRequest
     * @return
     *     returns it.isharedoc.schemas.instance.InstanceMessageCreateResponse
     */
    @WebMethod(operationName = "InstanceMessageCreate")
    @WebResult(name = "InstanceMessageCreateResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceMessageCreateResponse")
    public InstanceMessageCreateResponse instanceMessageCreate(
        @WebParam(name = "InstanceMessageCreateRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceMessageCreateRequest")
        InstanceMessageCreateRequest instanceMessageCreateRequest);

    /**
     * 
     * @param instanceDetailRequest
     * @return
     *     returns it.isharedoc.schemas.instance.InstanceDetailResponse
     */
    @WebMethod(operationName = "InstanceDetail")
    @WebResult(name = "InstanceDetailResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceDetailResponse")
    public InstanceDetailResponse instanceDetail(
        @WebParam(name = "InstanceDetailRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceDetailRequest")
        InstanceDetailRequest instanceDetailRequest);

    /**
     * 
     * @param instanceSearchRequest
     * @return
     *     returns it.isharedoc.schemas.instance.InstanceSearchResponse
     */
    @WebMethod(operationName = "InstanceSearch")
    @WebResult(name = "InstanceSearchResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceSearchResponse")
    public InstanceSearchResponse instanceSearch(
        @WebParam(name = "InstanceSearchRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceSearchRequest")
        InstanceSearchRequest instanceSearchRequest);

    /**
     * 
     * @param instanceSignalRequest
     * @return
     *     returns it.isharedoc.schemas.instance.InstanceSignalResponse
     */
    @WebMethod(operationName = "InstanceSignal")
    @WebResult(name = "InstanceSignalResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceSignalResponse")
    public InstanceSignalResponse instanceSignal(
        @WebParam(name = "InstanceSignalRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "InstanceSignalRequest")
        InstanceSignalRequest instanceSignalRequest);

    /**
     * 
     * @param taskCompleteRequest
     * @return
     *     returns it.isharedoc.schemas.instance.TaskCompleteResponse
     */
    @WebMethod(operationName = "TaskComplete")
    @WebResult(name = "TaskCompleteResponse", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "TaskCompleteResponse")
    public TaskCompleteResponse taskComplete(
        @WebParam(name = "TaskCompleteRequest", targetNamespace = "http://www.isharedoc.it/schemas/instance", partName = "TaskCompleteRequest")
        TaskCompleteRequest taskCompleteRequest);

}
