azienda:
    path:     /
    defaults: { _controller: "estarRdaBundle:Azienda:index" }

azienda_show:
    path:     /{id}/show
    defaults: { _controller: "estarRdaBundle:Azienda:show" }

azienda_new:
    path:     /new
    defaults: { _controller: "estarRdaBundle:Azienda:new" }

azienda_create:
    path:     /create
    defaults: { _controller: "estarRdaBundle:Azienda:create" }
    methods:  POST

azienda_edit:
    path:     /{id}/edit
    defaults: { _controller: "estarRdaBundle:Azienda:edit" }

azienda_update:
    path:     /{id}/update
    defaults: { _controller: "estarRdaBundle:Azienda:update" }
    methods:  [POST, PUT]

azienda_delete:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Azienda:delete" }
    methods:  [POST, DELETE]
