categoria:
    path:     /
    defaults: { _controller: "estarRdaBundle:Categoria:index" }

categoria_show:
    path:     /{id}/show
    defaults: { _controller: "estarRdaBundle:Categoria:show" }

categoria_new:
    path:     /new
    defaults: { _controller: "estarRdaBundle:Categoria:new" }

categoria_create:
    path:     /create
    defaults: { _controller: "estarRdaBundle:Categoria:create" }
    methods:  POST

categoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "estarRdaBundle:Categoria:edit" }

categoria_update:
    path:     /{id}/update
    defaults: { _controller: "estarRdaBundle:Categoria:update" }
    methods:  [POST, PUT]

categoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Categoria:delete" }
    methods:  [POST, DELETE]
