documento:
    path:     /
    defaults: { _controller: "estarRdaBundle:Documento:index" }

documento_show:
    path:     /{id}/show
    defaults: { _controller: "estarRdaBundle:Documento:show" }

documento_new:
    path:     /new
    defaults: { _controller: "estarRdaBundle:Documento:new" }

documento_create:
    path:     /create
    defaults: { _controller: "estarRdaBundle:Documento:create" }
    methods:  POST

documento_createlibero:
    path:     /createlibero/{idRichiesta}
    defaults: { _controller: "estarRdaBundle:Documento:createlibero" }
    methods:  POST

documento_edit:
    path:     /{id}/edit
    defaults: { _controller: "estarRdaBundle:Documento:edit" }

documento_update:
    path:     /{id}/update
    defaults: { _controller: "estarRdaBundle:Documento:update" }
    methods:  [POST, PUT]

documento_delete:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Documento:delete" }
    methods:  [POST, DELETE]

documento_byCategoria:
    path:     /byCategoria/{idCategoria}/{idRichiesta}
    defaults: { _controller: "estarRdaBundle:Documento:indexByCategoriaRichiesta" }

documento_liberoByRichiesta:
    path:     /liberoByRichiesta/{idRichiesta}/{idCategoria}
    defaults: { _controller: "estarRdaBundle:Documento:liberoByRichiesta" }

