documento:
    path:     /
    defaults: { _controller: "estarRdaBundle:Documento:index" }

documento_show:
    path:     /{id}/show
    defaults: { _controller: "estarRdaBundle:Documento:show" }

documento_new:
    path:     /new
    defaults: { _controller: "estarRdaBundle:Documento:new" }

documento_create:
    path:     /create
    defaults: { _controller: "estarRdaBundle:Documento:create" }
    methods:  POST

documento_edit:
    path:     /{id}/edit
    defaults: { _controller: "estarRdaBundle:Documento:edit" }

documento_update:
    path:     /{id}/update
    defaults: { _controller: "estarRdaBundle:Documento:update" }
    methods:  [POST, PUT]

documento_delete:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Documento:delete" }
    methods:  [POST, DELETE]
