formtemplate_show:
    path:     /show/{idCategoria}/{idRichiesta}
    defaults: { _controller: "estarRdaBundle:FormTemplate:show" }

formtempate_showpdf:
    path:     /showpdf/{idCategoria}/{idRichiesta}
    defaults: { _controller: "estarRdaBundle:FormTemplate:showpdf" }

formtemplate_new:
    path:     /{idCategoria}/new
    defaults: { _controller: "estarRdaBundle:FormTemplate:new" }

formtemplate_create:
    path:     /create/{idCategoria}
    defaults: { _controller: "estarRdaBundle:FormTemplate:create" }
    methods:  POST

formtemplate_edit:
    path:     /edit/{idCategoria}/{idRichiesta}
    defaults: { _controller: "estarRdaBundle:FormTemplate:edit" }

formtemplate_update:
    path:     /update/{idCategoria}/{idRichiesta}
    defaults: { _controller: "estarRdaBundle:FormTemplate:update" }
    methods:  [POST, PUT]

formtemplate_print:
    path:     /print/{idCategoria}/{idRichiesta}
    defaults: { _controller: "estarRdaBundle:FormTemplate:print" }
