gruppoutente:
    path:     /
    defaults: { _controller: "estarRdaBundle:Gruppoutente:index" }

gruppoutente_show:
    path:     /{id}/show
    defaults: { _controller: "estarRdaBundle:Gruppoutente:show" }

gruppoutente_new:
    path:     /new
    defaults: { _controller: "estarRdaBundle:Gruppoutente:new" }

gruppoutente_create:
    path:     /create
    defaults: { _controller: "estarRdaBundle:Gruppoutente:create" }
    methods:  POST

gruppoutente_edit:
    path:     /{id}/edit
    defaults: { _controller: "estarRdaBundle:Gruppoutente:edit" }

gruppoutente_update:
    path:     /{id}/update
    defaults: { _controller: "estarRdaBundle:Gruppoutente:update" }
    methods:  [POST, PUT]

gruppoutente_delete:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Gruppoutente:delete" }
    methods:  [POST, DELETE]
