richiesta:
    path:     /
    defaults: { _controller: "estarRdaBundle:Richiesta:index" }

richiesta_bycategoria:
    path:     /byCategoria/{idCategoria}
    defaults: { _controller: "estarRdaBundle:Richiesta:indexByCategoria" }
    options:
          expose: true

richiesta_show:
    path:     /{id}/show
    defaults: { _controller: "estarRdaBundle:Richiesta:show" }

richiesta_new:
    path:     /new
    defaults: { _controller: "estarRdaBundle:Richiesta:new" }

richiesta_create:
    path:     /create
    defaults: { _controller: "estarRdaBundle:Richiesta:create" }
    methods:  POST

richiesta_edit:
    path:     /{id}/edit
    defaults: { _controller: "estarRdaBundle:Richiesta:edit" }

richiesta_update:
    path:     /{id}/update
    defaults: { _controller: "estarRdaBundle:Richiesta:update" }
    methods:  [POST, PUT]

richiesta_delete:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Richiesta:delete" }
    methods:  [POST, DELETE]

richiesta_annulla:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Richiesta:annulla" }
    methods:  [POST, DELETE]

richiesta_valida:
    path:     /{id}/valida/{transizione}
    defaults: { _controller: "estarRdaBundle:Richiesta:valida" }
    methods:  POST

richiesta_clona:
    path:     /{id}/clona}
    defaults: { _controller: "estarRdaBundle:Richiesta:clona" }
    methods:  POST

richiesta_imponi_stato:
    path:     /imponistato/{id}
    defaults: { _controller: "estarRdaBundle:Richiesta:imponiStato" }
    methods:  [POST]

richiesta_viewall:
    path:     /view/{all}
    defaults: { _controller: "estarRdaBundle:Richiesta:viewAll" }
    options:
          expose: true

richiesta_aggregate:
    path:     /aggregate/{all}
    defaults: { _controller: "estarRdaBundle:Richiesta:aggregate" }
    options:
          expose: true

richiesta_globale:
    path:     /globale/{all}
    defaults: { _controller: "estarRdaBundle:Richiesta:globale" }
    options:
          expose: true