valorizzazionecamporichiesta:
    path:     /
    defaults: { _controller: "estarRdaBundle:Valorizzazionecamporichiesta:index" }

valorizzazionecamporichiesta_show:
    path:     /{id}/show
    defaults: { _controller: "estarRdaBundle:Valorizzazionecamporichiesta:show" }

valorizzazionecamporichiesta_new:
    path:     /new
    defaults: { _controller: "estarRdaBundle:Valorizzazionecamporichiesta:new" }

valorizzazionecamporichiesta_create:
    path:     /create
    defaults: { _controller: "estarRdaBundle:Valorizzazionecamporichiesta:create" }
    methods:  POST

valorizzazionecamporichiesta_edit:
    path:     /{id}/edit
    defaults: { _controller: "estarRdaBundle:Valorizzazionecamporichiesta:edit" }

valorizzazionecamporichiesta_update:
    path:     /{id}/update
    defaults: { _controller: "estarRdaBundle:Valorizzazionecamporichiesta:update" }
    methods:  [POST, PUT]

valorizzazionecamporichiesta_delete:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Valorizzazionecamporichiesta:delete" }
    methods:  [POST, DELETE]
