valorizzazionecampodocumento:
    path:     /
    defaults: { _controller: "estarRdaBundle:Valorizzazionecampodocumento:index" }

valorizzazionecampodocumento_show:
    path:     /{id}/show
    defaults: { _controller: "estarRdaBundle:Valorizzazionecampodocumento:show" }

valorizzazionecampodocumento_new:
    path:     /new
    defaults: { _controller: "estarRdaBundle:Valorizzazionecampodocumento:new" }

valorizzazionecampodocumento_create:
    path:     /create
    defaults: { _controller: "estarRdaBundle:Valorizzazionecampodocumento:create" }
    methods:  POST

valorizzazionecampodocumento_edit:
    path:     /{id}/edit
    defaults: { _controller: "estarRdaBundle:Valorizzazionecampodocumento:edit" }

valorizzazionecampodocumento_update:
    path:     /{id}/update
    defaults: { _controller: "estarRdaBundle:Valorizzazionecampodocumento:update" }
    methods:  [POST, PUT]

valorizzazionecampodocumento_delete:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Valorizzazionecampodocumento:delete" }
    methods:  [POST, DELETE]
