<?php

namespace Proxies\__CG__\estar\rda\RdaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Richiesta extends \estar\rda\RdaBundle\Entity\Richiesta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'numeropratica', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'status', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'numeroprotocollo', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'id', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'idcategoria', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'idazienda');
        }

        return array('__isInitialized__', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'numeropratica', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'status', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'numeroprotocollo', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'id', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'idcategoria', '' . "\0" . 'estar\\rda\\RdaBundle\\Entity\\Richiesta' . "\0" . 'idazienda');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Richiesta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNumeropratica($numeropratica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeropratica', array($numeropratica));

        return parent::setNumeropratica($numeropratica);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeropratica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeropratica', array());

        return parent::getNumeropratica();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroprotocollo($numeroprotocollo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroprotocollo', array($numeroprotocollo));

        return parent::setNumeroprotocollo($numeroprotocollo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroprotocollo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroprotocollo', array());

        return parent::getNumeroprotocollo();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcategoria(\estar\rda\RdaBundle\Entity\Categoria $idcategoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcategoria', array($idcategoria));

        return parent::setIdcategoria($idcategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcategoria', array());

        return parent::getIdcategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdazienda(\estar\rda\RdaBundle\Entity\Azienda $idazienda = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdazienda', array($idazienda));

        return parent::setIdazienda($idazienda);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdazienda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdazienda', array());

        return parent::getIdazienda();
    }

}
